// Generated by CoffeeScript 1.6.3
var LudiGame;

LudiGame = LudiGame || {};

LudiGame.app = {
  testTouch: function() {
    var div;
    div = document.querySelector('.test');
    div.addEventListener('touch', function() {
      console.log('clicked');
    });
  }
};

LudiGame.app.testTouch();
